---
- name: Load the blueprints into osbuild
  infra.osbuild.push_blueprint:
    blueprint: '{{ lookup("template", "blueprint.toml.j2") }}'

- name: Start compose
  infra.osbuild.start_compose:
    blueprint: "{{ blueprint.name }}"
    compose_type: edge-commit
    allow_duplicate: false
  register: builder_compose

- name: Wait for compose to finish
  infra.osbuild.wait_compose:
    compose_id: "{{ compose_id }}"
    timeout: 3600
  when: builder_compose.changed
